[project]
name = "raven"
authors = [
    { name = "The Commit Company", email = "support@thecommit.company"}
]
description = "Simple, open source messaging tool"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
 "linkpreview",
 "firebase-admin~=6.2.0"
]